//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhishingReporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhishingReporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! The email you reported was a simulated phishing attack initiated by Company ICT. Good job!.
        /// </summary>
        internal static string FakeMessage_Text_english {
            get {
                return ResourceManager.GetString("FakeMessage_Text_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glückwünsch! Bei diesem E-Mail handelte es sich um eine simulierte Phishing-Attacke von Firmen ICT. Sie haben richtig reagiert!.
        /// </summary>
        internal static string FakeMessage_Text_german {
            get {
                return ResourceManager.GetString("FakeMessage_Text_german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo___ICT_SEC {
            get {
                object obj = ResourceManager.GetObject("Logo - ICT-SEC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company - ICT Security.
        /// </summary>
        internal static string MessageBox_Title {
            get {
                return ResourceManager.GetString("MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a message To Continue.
        /// </summary>
        internal static string NoMessageText_english {
            get {
                return ResourceManager.GetString("NoMessageText_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte eine Nachricht markieren.
        /// </summary>
        internal static string NoMessageText_german {
            get {
                return ResourceManager.GetString("NoMessageText_german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for helping to make our Company more secure.
        /// </summary>
        internal static string ThankYouMsgBox_Text_english {
            get {
                return ResourceManager.GetString("ThankYouMsgBox_Text_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank für Ihre mithilfe die Firma sicherer zu machen.
        /// </summary>
        internal static string ThankYouMsgBox_Text_german {
            get {
                return ResourceManager.GetString("ThankYouMsgBox_Text_german", resourceCulture);
            }
        }
    }
}
